
CREATE DATABASE schbsddb;

USE schbsddb;

CREATE TABLE SESSION_LINE (
  `uuid`      CHAR(32) NOT NULL,
  `key`       VARCHAR(64) NOT NULL, 
  `value`     VARCHAR(256) NOT NULL DEFAULT "",
  `overtime`  DATETIME NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CAPTCHA_DATAS (
  `id`       CHAR(20) NOT NULL PRIMARY KEY,
  `value`    CHAR(6) NOT NULL,
  `overtime` DATETIME NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USERS (
  `id`          INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `username`    VARCHAR(32) UNIQUE NOT NULL,
  `password`    CHAR(64) NOT NULL,
  `verified`    BOOLEAN NOT NULL DEFAULT FALSE,
  `frozen`      BOOLEAN NOT NULL DEFAULT FALSE,
  `manager`     INTEGER UNSIGNED,
  FOREIGN KEY user_id(`manager`) REFERENCES USERS(`id`) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE QUESTIONS (
  `id`       INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `quest`    VARCHAR(255) NOT NULL,
  `answer`   VARCHAR(127) NOT NULL,
  `owner`    INTEGER UNSIGNED,
  `verified` BOOLEAN NOT NULL DEFAULT FALSE,
  FOREIGN KEY user_id(`owner`) REFERENCES USERS(`id`) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE MATCHS (
  `id`       CHAR(32) PRIMARY KEY,
  `questnum` INTEGER NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE MATCH_USERS (
  `id`      CHAR(32) PRIMARY KEY,
  `matchid` CHAR(32) NOT NULL,
  `userid`  INTEGER UNSIGNED NOT NULL,
  FOREIGN KEY match_id(`matchid`) REFERENCES MATCHS(`id`) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY user_id(`userid`) REFERENCES USERS(`id`) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE MATCH_ANSWERS (
  `muserid` CHAR(32) NOT NULL,
  `questid` INTEGER UNSIGNED NOT NULL,
  `answer`  VARCHAR(127) NOT NULL,
  `score`   INTEGER NOT NULL,
  FOREIGN KEY match_user_id(`muserid`) REFERENCES MATCH_USERS(`id`) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY quest_id(`questid`) REFERENCES QUESTIONS(`id`) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

